services:

  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./secrets/userauth-pass:/run/secrets/userauth-pass:ro
    ports:
      - "5432:5432"
    environment:
      DB_HOST: db
      POSTGRES_DB: userauth
      POSTGRES_USER: userauth
      POSTGRES_PASSWORD_FILE: /run/secrets/userauth-pass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U userauth"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  pdf_storage:
    image: minio/minio:latest
    restart: always
    volumes:
      - minio_data:/var/lib/minio_data
      - ./secrets/pdfstore-pass:/run/secrets/pdfstore-pass:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: pdfstore
      MINIO_ROOT_PASSWORD_FILE: /run/secrets/pdfstore-pass
    command: server /var/lib/minio_data --console-address ":9001"

  db_init:
    build: ./app/user-auth
    restart: "no"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./secrets/userauth-pass:/run/secrets/userauth-pass:ro
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=userauth
      - DB_USER=userauth

volumes:
  postgres_data:
  minio_data:
