FROM python:3.10-slim

WORKDIR /app
ENV PYTHONPATH=/app \
    PYTHONUNBUFFERED=1

COPY api/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


RUN python -c "from sentence_transformers import SentenceTransformer; SentenceTransformer('all-MiniLM-L6-v2')"

COPY . .

EXPOSE 5000


CMD ["gunicorn", \
     "--workers=4", \
     "--threads=2", \
     "--worker-class=gthread", \
     "--bind=0.0.0.0:5000", \
     "--timeout=120", \
     "--preload", \
     "--access-logfile=-", \
     "--error-logfile=-", \
     "--chdir=/app/api", \
     "main:app"]
